# Generated by Django 5.2.1 on 2025-05-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(verbose_name=100)),
                ('telefone', models.CharField(verbose_name=20)),
            ],
        ),
    ]
