# Generated by Django 5.2.1 on 2025-05-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_produto_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='data',
            new_name='data_criacao',
        ),
        migrations.AddField(
            model_name='produto',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
